server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
info:
  app.name: hnx-microservicecloud
  company.name: www.dadedawei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
zuul: 
  prefix: /dadedawei     # 设置统一的服务地址前缀
  ignored-services: "*" # 禁止所有的服务器真实名称
  # ignored-services: microservicecloud-dept  # 配置不能用原真实名映射
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**     # zuul的路由映射地址

